module.exports = {
  'CROSSING': 'CROSSING',
  'CROSSING_ON_CLOSE': 'CROSSING_ON_CLOSE',
  'CROSSING_UP': 'CROSSING_UP',
  'CROSSING_DOWN': 'CROSSING_DOWN',
  'CROSSING_UP_ON_CLOSE': 'CROSSING_UP_ON_CLOSE',
  'CROSSING_DOWN_ON_CLOSE': 'CROSSING_DOWN_ON_CLOSE'
};